platform :ios, "6.0"

target "FontAwesomeKitTestHost" do
  pod 'FontAwesomeKit', :podspec => '../FontAwesomeKit.podspec'
end

target "FontAwesomeKitTestHostTests" do
  pod 'OCHamcrest'
  pod 'OCMockito'
end

