#import "FAKIcon.h"

@interface FAKIonIcons : FAKIcon

// Generated Code
+ (instancetype)alertIconWithSize:(CGFloat)size;
+ (instancetype)alertCircledIconWithSize:(CGFloat)size;
+ (instancetype)androidAddIconWithSize:(CGFloat)size;
+ (instancetype)androidAddCircleIconWithSize:(CGFloat)size;
+ (instancetype)androidAlarmClockIconWithSize:(CGFloat)size;
+ (instancetype)androidAlertIconWithSize:(CGFloat)size;
+ (instancetype)androidAppsIconWithSize:(CGFloat)size;
+ (instancetype)androidArchiveIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowBackIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDownIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDropdownIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDropdownCircleIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDropleftIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDropleftCircleIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDroprightIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDroprightCircleIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDropupIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowDropupCircleIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowForwardIconWithSize:(CGFloat)size;
+ (instancetype)androidArrowUpIconWithSize:(CGFloat)size;
+ (instancetype)androidAttachIconWithSize:(CGFloat)size;
+ (instancetype)androidBarIconWithSize:(CGFloat)size;
+ (instancetype)androidBicycleIconWithSize:(CGFloat)size;
+ (instancetype)androidBoatIconWithSize:(CGFloat)size;
+ (instancetype)androidBookmarkIconWithSize:(CGFloat)size;
+ (instancetype)androidBulbIconWithSize:(CGFloat)size;
+ (instancetype)androidBusIconWithSize:(CGFloat)size;
+ (instancetype)androidCalendarIconWithSize:(CGFloat)size;
+ (instancetype)androidCallIconWithSize:(CGFloat)size;
+ (instancetype)androidCameraIconWithSize:(CGFloat)size;
+ (instancetype)androidCancelIconWithSize:(CGFloat)size;
+ (instancetype)androidCarIconWithSize:(CGFloat)size;
+ (instancetype)androidCartIconWithSize:(CGFloat)size;
+ (instancetype)androidChatIconWithSize:(CGFloat)size;
+ (instancetype)androidCheckboxIconWithSize:(CGFloat)size;
+ (instancetype)androidCheckboxBlankIconWithSize:(CGFloat)size;
+ (instancetype)androidCheckboxOutlineIconWithSize:(CGFloat)size;
+ (instancetype)androidCheckboxOutlineBlankIconWithSize:(CGFloat)size;
+ (instancetype)androidCheckmarkCircleIconWithSize:(CGFloat)size;
+ (instancetype)androidClipboardIconWithSize:(CGFloat)size;
+ (instancetype)androidCloseIconWithSize:(CGFloat)size;
+ (instancetype)androidCloudIconWithSize:(CGFloat)size;
+ (instancetype)androidCloudCircleIconWithSize:(CGFloat)size;
+ (instancetype)androidCloudDoneIconWithSize:(CGFloat)size;
+ (instancetype)androidCloudOutlineIconWithSize:(CGFloat)size;
+ (instancetype)androidColorPaletteIconWithSize:(CGFloat)size;
+ (instancetype)androidCompassIconWithSize:(CGFloat)size;
+ (instancetype)androidContactIconWithSize:(CGFloat)size;
+ (instancetype)androidContactsIconWithSize:(CGFloat)size;
+ (instancetype)androidContractIconWithSize:(CGFloat)size;
+ (instancetype)androidCreateIconWithSize:(CGFloat)size;
+ (instancetype)androidDeleteIconWithSize:(CGFloat)size;
+ (instancetype)androidDesktopIconWithSize:(CGFloat)size;
+ (instancetype)androidDocumentIconWithSize:(CGFloat)size;
+ (instancetype)androidDoneIconWithSize:(CGFloat)size;
+ (instancetype)androidDoneAllIconWithSize:(CGFloat)size;
+ (instancetype)androidDownloadIconWithSize:(CGFloat)size;
+ (instancetype)androidDraftsIconWithSize:(CGFloat)size;
+ (instancetype)androidExitIconWithSize:(CGFloat)size;
+ (instancetype)androidExpandIconWithSize:(CGFloat)size;
+ (instancetype)androidFavoriteIconWithSize:(CGFloat)size;
+ (instancetype)androidFavoriteOutlineIconWithSize:(CGFloat)size;
+ (instancetype)androidFilmIconWithSize:(CGFloat)size;
+ (instancetype)androidFolderIconWithSize:(CGFloat)size;
+ (instancetype)androidFolderOpenIconWithSize:(CGFloat)size;
+ (instancetype)androidFunnelIconWithSize:(CGFloat)size;
+ (instancetype)androidGlobeIconWithSize:(CGFloat)size;
+ (instancetype)androidHandIconWithSize:(CGFloat)size;
+ (instancetype)androidHangoutIconWithSize:(CGFloat)size;
+ (instancetype)androidHappyIconWithSize:(CGFloat)size;
+ (instancetype)androidHomeIconWithSize:(CGFloat)size;
+ (instancetype)androidImageIconWithSize:(CGFloat)size;
+ (instancetype)androidLaptopIconWithSize:(CGFloat)size;
+ (instancetype)androidListIconWithSize:(CGFloat)size;
+ (instancetype)androidLocateIconWithSize:(CGFloat)size;
+ (instancetype)androidLockIconWithSize:(CGFloat)size;
+ (instancetype)androidMailIconWithSize:(CGFloat)size;
+ (instancetype)androidMapIconWithSize:(CGFloat)size;
+ (instancetype)androidMenuIconWithSize:(CGFloat)size;
+ (instancetype)androidMicrophoneIconWithSize:(CGFloat)size;
+ (instancetype)androidMicrophoneOffIconWithSize:(CGFloat)size;
+ (instancetype)androidMoreHorizontalIconWithSize:(CGFloat)size;
+ (instancetype)androidMoreVerticalIconWithSize:(CGFloat)size;
+ (instancetype)androidNavigateIconWithSize:(CGFloat)size;
+ (instancetype)androidNotificationsIconWithSize:(CGFloat)size;
+ (instancetype)androidNotificationsNoneIconWithSize:(CGFloat)size;
+ (instancetype)androidNotificationsOffIconWithSize:(CGFloat)size;
+ (instancetype)androidOpenIconWithSize:(CGFloat)size;
+ (instancetype)androidOptionsIconWithSize:(CGFloat)size;
+ (instancetype)androidPeopleIconWithSize:(CGFloat)size;
+ (instancetype)androidPersonIconWithSize:(CGFloat)size;
+ (instancetype)androidPersonAddIconWithSize:(CGFloat)size;
+ (instancetype)androidPhoneLandscapeIconWithSize:(CGFloat)size;
+ (instancetype)androidPhonePortraitIconWithSize:(CGFloat)size;
+ (instancetype)androidPinIconWithSize:(CGFloat)size;
+ (instancetype)androidPlaneIconWithSize:(CGFloat)size;
+ (instancetype)androidPlaystoreIconWithSize:(CGFloat)size;
+ (instancetype)androidPrintIconWithSize:(CGFloat)size;
+ (instancetype)androidRadioButtonOffIconWithSize:(CGFloat)size;
+ (instancetype)androidRadioButtonOnIconWithSize:(CGFloat)size;
+ (instancetype)androidRefreshIconWithSize:(CGFloat)size;
+ (instancetype)androidRemoveIconWithSize:(CGFloat)size;
+ (instancetype)androidRemoveCircleIconWithSize:(CGFloat)size;
+ (instancetype)androidRestaurantIconWithSize:(CGFloat)size;
+ (instancetype)androidSadIconWithSize:(CGFloat)size;
+ (instancetype)androidSearchIconWithSize:(CGFloat)size;
+ (instancetype)androidSendIconWithSize:(CGFloat)size;
+ (instancetype)androidSettingsIconWithSize:(CGFloat)size;
+ (instancetype)androidShareIconWithSize:(CGFloat)size;
+ (instancetype)androidShareAltIconWithSize:(CGFloat)size;
+ (instancetype)androidStarIconWithSize:(CGFloat)size;
+ (instancetype)androidStarHalfIconWithSize:(CGFloat)size;
+ (instancetype)androidStarOutlineIconWithSize:(CGFloat)size;
+ (instancetype)androidStopwatchIconWithSize:(CGFloat)size;
+ (instancetype)androidSubwayIconWithSize:(CGFloat)size;
+ (instancetype)androidSunnyIconWithSize:(CGFloat)size;
+ (instancetype)androidSyncIconWithSize:(CGFloat)size;
+ (instancetype)androidTextsmsIconWithSize:(CGFloat)size;
+ (instancetype)androidTimeIconWithSize:(CGFloat)size;
+ (instancetype)androidTrainIconWithSize:(CGFloat)size;
+ (instancetype)androidUnlockIconWithSize:(CGFloat)size;
+ (instancetype)androidUploadIconWithSize:(CGFloat)size;
+ (instancetype)androidVolumeDownIconWithSize:(CGFloat)size;
+ (instancetype)androidVolumeMuteIconWithSize:(CGFloat)size;
+ (instancetype)androidVolumeOffIconWithSize:(CGFloat)size;
+ (instancetype)androidVolumeUpIconWithSize:(CGFloat)size;
+ (instancetype)androidWalkIconWithSize:(CGFloat)size;
+ (instancetype)androidWarningIconWithSize:(CGFloat)size;
+ (instancetype)androidWatchIconWithSize:(CGFloat)size;
+ (instancetype)androidWifiIconWithSize:(CGFloat)size;
+ (instancetype)apertureIconWithSize:(CGFloat)size;
+ (instancetype)archiveIconWithSize:(CGFloat)size;
+ (instancetype)arrowDownAIconWithSize:(CGFloat)size;
+ (instancetype)arrowDownBIconWithSize:(CGFloat)size;
+ (instancetype)arrowDownCIconWithSize:(CGFloat)size;
+ (instancetype)arrowExpandIconWithSize:(CGFloat)size;
+ (instancetype)arrowGraphDownLeftIconWithSize:(CGFloat)size;
+ (instancetype)arrowGraphDownRightIconWithSize:(CGFloat)size;
+ (instancetype)arrowGraphUpLeftIconWithSize:(CGFloat)size;
+ (instancetype)arrowGraphUpRightIconWithSize:(CGFloat)size;
+ (instancetype)arrowLeftAIconWithSize:(CGFloat)size;
+ (instancetype)arrowLeftBIconWithSize:(CGFloat)size;
+ (instancetype)arrowLeftCIconWithSize:(CGFloat)size;
+ (instancetype)arrowMoveIconWithSize:(CGFloat)size;
+ (instancetype)arrowResizeIconWithSize:(CGFloat)size;
+ (instancetype)arrowReturnLeftIconWithSize:(CGFloat)size;
+ (instancetype)arrowReturnRightIconWithSize:(CGFloat)size;
+ (instancetype)arrowRightAIconWithSize:(CGFloat)size;
+ (instancetype)arrowRightBIconWithSize:(CGFloat)size;
+ (instancetype)arrowRightCIconWithSize:(CGFloat)size;
+ (instancetype)arrowShrinkIconWithSize:(CGFloat)size;
+ (instancetype)arrowSwapIconWithSize:(CGFloat)size;
+ (instancetype)arrowUpAIconWithSize:(CGFloat)size;
+ (instancetype)arrowUpBIconWithSize:(CGFloat)size;
+ (instancetype)arrowUpCIconWithSize:(CGFloat)size;
+ (instancetype)asteriskIconWithSize:(CGFloat)size;
+ (instancetype)atIconWithSize:(CGFloat)size;
+ (instancetype)backspaceIconWithSize:(CGFloat)size;
+ (instancetype)backspaceOutlineIconWithSize:(CGFloat)size;
+ (instancetype)bagIconWithSize:(CGFloat)size;
+ (instancetype)batteryChargingIconWithSize:(CGFloat)size;
+ (instancetype)batteryEmptyIconWithSize:(CGFloat)size;
+ (instancetype)batteryFullIconWithSize:(CGFloat)size;
+ (instancetype)batteryHalfIconWithSize:(CGFloat)size;
+ (instancetype)batteryLowIconWithSize:(CGFloat)size;
+ (instancetype)beakerIconWithSize:(CGFloat)size;
+ (instancetype)beerIconWithSize:(CGFloat)size;
+ (instancetype)bluetoothIconWithSize:(CGFloat)size;
+ (instancetype)bonfireIconWithSize:(CGFloat)size;
+ (instancetype)bookmarkIconWithSize:(CGFloat)size;
+ (instancetype)bowtieIconWithSize:(CGFloat)size;
+ (instancetype)briefcaseIconWithSize:(CGFloat)size;
+ (instancetype)bugIconWithSize:(CGFloat)size;
+ (instancetype)calculatorIconWithSize:(CGFloat)size;
+ (instancetype)calendarIconWithSize:(CGFloat)size;
+ (instancetype)cameraIconWithSize:(CGFloat)size;
+ (instancetype)cardIconWithSize:(CGFloat)size;
+ (instancetype)cashIconWithSize:(CGFloat)size;
+ (instancetype)chatboxIconWithSize:(CGFloat)size;
+ (instancetype)chatboxWorkingIconWithSize:(CGFloat)size;
+ (instancetype)chatboxesIconWithSize:(CGFloat)size;
+ (instancetype)chatbubbleIconWithSize:(CGFloat)size;
+ (instancetype)chatbubbleWorkingIconWithSize:(CGFloat)size;
+ (instancetype)chatbubblesIconWithSize:(CGFloat)size;
+ (instancetype)checkmarkIconWithSize:(CGFloat)size;
+ (instancetype)checkmarkCircledIconWithSize:(CGFloat)size;
+ (instancetype)checkmarkRoundIconWithSize:(CGFloat)size;
+ (instancetype)chevronDownIconWithSize:(CGFloat)size;
+ (instancetype)chevronLeftIconWithSize:(CGFloat)size;
+ (instancetype)chevronRightIconWithSize:(CGFloat)size;
+ (instancetype)chevronUpIconWithSize:(CGFloat)size;
+ (instancetype)clipboardIconWithSize:(CGFloat)size;
+ (instancetype)clockIconWithSize:(CGFloat)size;
+ (instancetype)closeIconWithSize:(CGFloat)size;
+ (instancetype)closeCircledIconWithSize:(CGFloat)size;
+ (instancetype)closeRoundIconWithSize:(CGFloat)size;
+ (instancetype)closedCaptioningIconWithSize:(CGFloat)size;
+ (instancetype)cloudIconWithSize:(CGFloat)size;
+ (instancetype)codeIconWithSize:(CGFloat)size;
+ (instancetype)codeDownloadIconWithSize:(CGFloat)size;
+ (instancetype)codeWorkingIconWithSize:(CGFloat)size;
+ (instancetype)coffeeIconWithSize:(CGFloat)size;
+ (instancetype)compassIconWithSize:(CGFloat)size;
+ (instancetype)composeIconWithSize:(CGFloat)size;
+ (instancetype)connectionBarsIconWithSize:(CGFloat)size;
+ (instancetype)contrastIconWithSize:(CGFloat)size;
+ (instancetype)cropIconWithSize:(CGFloat)size;
+ (instancetype)cubeIconWithSize:(CGFloat)size;
+ (instancetype)discIconWithSize:(CGFloat)size;
+ (instancetype)documentIconWithSize:(CGFloat)size;
+ (instancetype)documentTextIconWithSize:(CGFloat)size;
+ (instancetype)dragIconWithSize:(CGFloat)size;
+ (instancetype)earthIconWithSize:(CGFloat)size;
+ (instancetype)easelIconWithSize:(CGFloat)size;
+ (instancetype)editIconWithSize:(CGFloat)size;
+ (instancetype)eggIconWithSize:(CGFloat)size;
+ (instancetype)ejectIconWithSize:(CGFloat)size;
+ (instancetype)emailIconWithSize:(CGFloat)size;
+ (instancetype)emailUnreadIconWithSize:(CGFloat)size;
+ (instancetype)erlenmeyerFlaskIconWithSize:(CGFloat)size;
+ (instancetype)erlenmeyerFlaskBubblesIconWithSize:(CGFloat)size;
+ (instancetype)eyeIconWithSize:(CGFloat)size;
+ (instancetype)eyeDisabledIconWithSize:(CGFloat)size;
+ (instancetype)femaleIconWithSize:(CGFloat)size;
+ (instancetype)filingIconWithSize:(CGFloat)size;
+ (instancetype)filmMarkerIconWithSize:(CGFloat)size;
+ (instancetype)fireballIconWithSize:(CGFloat)size;
+ (instancetype)flagIconWithSize:(CGFloat)size;
+ (instancetype)flameIconWithSize:(CGFloat)size;
+ (instancetype)flashIconWithSize:(CGFloat)size;
+ (instancetype)flashOffIconWithSize:(CGFloat)size;
+ (instancetype)folderIconWithSize:(CGFloat)size;
+ (instancetype)forkIconWithSize:(CGFloat)size;
+ (instancetype)forkRepoIconWithSize:(CGFloat)size;
+ (instancetype)forwardIconWithSize:(CGFloat)size;
+ (instancetype)funnelIconWithSize:(CGFloat)size;
+ (instancetype)gearAIconWithSize:(CGFloat)size;
+ (instancetype)gearBIconWithSize:(CGFloat)size;
+ (instancetype)gridIconWithSize:(CGFloat)size;
+ (instancetype)hammerIconWithSize:(CGFloat)size;
+ (instancetype)happyIconWithSize:(CGFloat)size;
+ (instancetype)happyOutlineIconWithSize:(CGFloat)size;
+ (instancetype)headphoneIconWithSize:(CGFloat)size;
+ (instancetype)heartIconWithSize:(CGFloat)size;
+ (instancetype)heartBrokenIconWithSize:(CGFloat)size;
+ (instancetype)helpIconWithSize:(CGFloat)size;
+ (instancetype)helpBuoyIconWithSize:(CGFloat)size;
+ (instancetype)helpCircledIconWithSize:(CGFloat)size;
+ (instancetype)homeIconWithSize:(CGFloat)size;
+ (instancetype)icecreamIconWithSize:(CGFloat)size;
+ (instancetype)imageIconWithSize:(CGFloat)size;
+ (instancetype)imagesIconWithSize:(CGFloat)size;
+ (instancetype)informationIconWithSize:(CGFloat)size;
+ (instancetype)informationCircledIconWithSize:(CGFloat)size;
+ (instancetype)ionicIconWithSize:(CGFloat)size;
+ (instancetype)iosAlarmIconWithSize:(CGFloat)size;
+ (instancetype)iosAlarmOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosAlbumsIconWithSize:(CGFloat)size;
+ (instancetype)iosAlbumsOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosAmericanfootballIconWithSize:(CGFloat)size;
+ (instancetype)iosAmericanfootballOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosAnalyticsIconWithSize:(CGFloat)size;
+ (instancetype)iosAnalyticsOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowBackIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowDownIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowForwardIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowLeftIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowRightIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowThinDownIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowThinLeftIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowThinRightIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowThinUpIconWithSize:(CGFloat)size;
+ (instancetype)iosArrowUpIconWithSize:(CGFloat)size;
+ (instancetype)iosAtIconWithSize:(CGFloat)size;
+ (instancetype)iosAtOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBarcodeIconWithSize:(CGFloat)size;
+ (instancetype)iosBarcodeOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBaseballIconWithSize:(CGFloat)size;
+ (instancetype)iosBaseballOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBasketballIconWithSize:(CGFloat)size;
+ (instancetype)iosBasketballOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBellIconWithSize:(CGFloat)size;
+ (instancetype)iosBellOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBodyIconWithSize:(CGFloat)size;
+ (instancetype)iosBodyOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBoltIconWithSize:(CGFloat)size;
+ (instancetype)iosBoltOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBookIconWithSize:(CGFloat)size;
+ (instancetype)iosBookOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBookmarksIconWithSize:(CGFloat)size;
+ (instancetype)iosBookmarksOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBoxIconWithSize:(CGFloat)size;
+ (instancetype)iosBoxOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBriefcaseIconWithSize:(CGFloat)size;
+ (instancetype)iosBriefcaseOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosBrowsersIconWithSize:(CGFloat)size;
+ (instancetype)iosBrowsersOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCalculatorIconWithSize:(CGFloat)size;
+ (instancetype)iosCalculatorOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCalendarIconWithSize:(CGFloat)size;
+ (instancetype)iosCalendarOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCameraIconWithSize:(CGFloat)size;
+ (instancetype)iosCameraOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCartIconWithSize:(CGFloat)size;
+ (instancetype)iosCartOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosChatboxesIconWithSize:(CGFloat)size;
+ (instancetype)iosChatboxesOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosChatbubbleIconWithSize:(CGFloat)size;
+ (instancetype)iosChatbubbleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCheckmarkIconWithSize:(CGFloat)size;
+ (instancetype)iosCheckmarkEmptyIconWithSize:(CGFloat)size;
+ (instancetype)iosCheckmarkOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCircleFilledIconWithSize:(CGFloat)size;
+ (instancetype)iosCircleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosClockIconWithSize:(CGFloat)size;
+ (instancetype)iosClockOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCloseIconWithSize:(CGFloat)size;
+ (instancetype)iosCloseEmptyIconWithSize:(CGFloat)size;
+ (instancetype)iosCloseOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudDownloadIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudDownloadOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudUploadIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudUploadOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudyIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudyNightIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudyNightOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCloudyOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCogIconWithSize:(CGFloat)size;
+ (instancetype)iosCogOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosColorFilterIconWithSize:(CGFloat)size;
+ (instancetype)iosColorFilterOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosColorWandIconWithSize:(CGFloat)size;
+ (instancetype)iosColorWandOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosComposeIconWithSize:(CGFloat)size;
+ (instancetype)iosComposeOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosContactIconWithSize:(CGFloat)size;
+ (instancetype)iosContactOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCopyIconWithSize:(CGFloat)size;
+ (instancetype)iosCopyOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosCropIconWithSize:(CGFloat)size;
+ (instancetype)iosCropStrongIconWithSize:(CGFloat)size;
+ (instancetype)iosDownloadIconWithSize:(CGFloat)size;
+ (instancetype)iosDownloadOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosDragIconWithSize:(CGFloat)size;
+ (instancetype)iosEmailIconWithSize:(CGFloat)size;
+ (instancetype)iosEmailOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosEyeIconWithSize:(CGFloat)size;
+ (instancetype)iosEyeOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFastforwardIconWithSize:(CGFloat)size;
+ (instancetype)iosFastforwardOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFilingIconWithSize:(CGFloat)size;
+ (instancetype)iosFilingOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFilmIconWithSize:(CGFloat)size;
+ (instancetype)iosFilmOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFlagIconWithSize:(CGFloat)size;
+ (instancetype)iosFlagOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFlameIconWithSize:(CGFloat)size;
+ (instancetype)iosFlameOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFlaskIconWithSize:(CGFloat)size;
+ (instancetype)iosFlaskOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFlowerIconWithSize:(CGFloat)size;
+ (instancetype)iosFlowerOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFolderIconWithSize:(CGFloat)size;
+ (instancetype)iosFolderOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosFootballIconWithSize:(CGFloat)size;
+ (instancetype)iosFootballOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosGameControllerAIconWithSize:(CGFloat)size;
+ (instancetype)iosGameControllerAOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosGameControllerBIconWithSize:(CGFloat)size;
+ (instancetype)iosGameControllerBOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosGearIconWithSize:(CGFloat)size;
+ (instancetype)iosGearOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosGlassesIconWithSize:(CGFloat)size;
+ (instancetype)iosGlassesOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosGridViewIconWithSize:(CGFloat)size;
+ (instancetype)iosGridViewOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosHeartIconWithSize:(CGFloat)size;
+ (instancetype)iosHeartOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosHelpIconWithSize:(CGFloat)size;
+ (instancetype)iosHelpEmptyIconWithSize:(CGFloat)size;
+ (instancetype)iosHelpOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosHomeIconWithSize:(CGFloat)size;
+ (instancetype)iosHomeOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosInfiniteIconWithSize:(CGFloat)size;
+ (instancetype)iosInfiniteOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosInformationIconWithSize:(CGFloat)size;
+ (instancetype)iosInformationEmptyIconWithSize:(CGFloat)size;
+ (instancetype)iosInformationOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosIonicOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosKeypadIconWithSize:(CGFloat)size;
+ (instancetype)iosKeypadOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosLightbulbIconWithSize:(CGFloat)size;
+ (instancetype)iosLightbulbOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosListIconWithSize:(CGFloat)size;
+ (instancetype)iosListOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosLocationIconWithSize:(CGFloat)size;
+ (instancetype)iosLocationOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosLockedIconWithSize:(CGFloat)size;
+ (instancetype)iosLockedOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosLoopIconWithSize:(CGFloat)size;
+ (instancetype)iosLoopStrongIconWithSize:(CGFloat)size;
+ (instancetype)iosMedicalIconWithSize:(CGFloat)size;
+ (instancetype)iosMedicalOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosMedkitIconWithSize:(CGFloat)size;
+ (instancetype)iosMedkitOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosMicIconWithSize:(CGFloat)size;
+ (instancetype)iosMicOffIconWithSize:(CGFloat)size;
+ (instancetype)iosMicOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosMinusIconWithSize:(CGFloat)size;
+ (instancetype)iosMinusEmptyIconWithSize:(CGFloat)size;
+ (instancetype)iosMinusOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosMonitorIconWithSize:(CGFloat)size;
+ (instancetype)iosMonitorOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosMoonIconWithSize:(CGFloat)size;
+ (instancetype)iosMoonOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosMoreIconWithSize:(CGFloat)size;
+ (instancetype)iosMoreOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosMusicalNoteIconWithSize:(CGFloat)size;
+ (instancetype)iosMusicalNotesIconWithSize:(CGFloat)size;
+ (instancetype)iosNavigateIconWithSize:(CGFloat)size;
+ (instancetype)iosNavigateOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosNutritionIconWithSize:(CGFloat)size;
+ (instancetype)iosNutritionOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPaperIconWithSize:(CGFloat)size;
+ (instancetype)iosPaperOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPaperplaneIconWithSize:(CGFloat)size;
+ (instancetype)iosPaperplaneOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPartlysunnyIconWithSize:(CGFloat)size;
+ (instancetype)iosPartlysunnyOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPauseIconWithSize:(CGFloat)size;
+ (instancetype)iosPauseOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPawIconWithSize:(CGFloat)size;
+ (instancetype)iosPawOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPeopleIconWithSize:(CGFloat)size;
+ (instancetype)iosPeopleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPersonIconWithSize:(CGFloat)size;
+ (instancetype)iosPersonOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPersonaddIconWithSize:(CGFloat)size;
+ (instancetype)iosPersonaddOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPhotosIconWithSize:(CGFloat)size;
+ (instancetype)iosPhotosOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPieIconWithSize:(CGFloat)size;
+ (instancetype)iosPieOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPintIconWithSize:(CGFloat)size;
+ (instancetype)iosPintOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPlayIconWithSize:(CGFloat)size;
+ (instancetype)iosPlayOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPlusIconWithSize:(CGFloat)size;
+ (instancetype)iosPlusEmptyIconWithSize:(CGFloat)size;
+ (instancetype)iosPlusOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPricetagIconWithSize:(CGFloat)size;
+ (instancetype)iosPricetagOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPricetagsIconWithSize:(CGFloat)size;
+ (instancetype)iosPricetagsOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPrinterIconWithSize:(CGFloat)size;
+ (instancetype)iosPrinterOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosPulseIconWithSize:(CGFloat)size;
+ (instancetype)iosPulseStrongIconWithSize:(CGFloat)size;
+ (instancetype)iosRainyIconWithSize:(CGFloat)size;
+ (instancetype)iosRainyOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosRecordingIconWithSize:(CGFloat)size;
+ (instancetype)iosRecordingOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosRedoIconWithSize:(CGFloat)size;
+ (instancetype)iosRedoOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosRefreshIconWithSize:(CGFloat)size;
+ (instancetype)iosRefreshEmptyIconWithSize:(CGFloat)size;
+ (instancetype)iosRefreshOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosReloadIconWithSize:(CGFloat)size;
+ (instancetype)iosReverseCameraIconWithSize:(CGFloat)size;
+ (instancetype)iosReverseCameraOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosRewindIconWithSize:(CGFloat)size;
+ (instancetype)iosRewindOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosRoseIconWithSize:(CGFloat)size;
+ (instancetype)iosRoseOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosSearchIconWithSize:(CGFloat)size;
+ (instancetype)iosSearchStrongIconWithSize:(CGFloat)size;
+ (instancetype)iosSettingsIconWithSize:(CGFloat)size;
+ (instancetype)iosSettingsStrongIconWithSize:(CGFloat)size;
+ (instancetype)iosShuffleIconWithSize:(CGFloat)size;
+ (instancetype)iosShuffleStrongIconWithSize:(CGFloat)size;
+ (instancetype)iosSkipbackwardIconWithSize:(CGFloat)size;
+ (instancetype)iosSkipbackwardOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosSkipforwardIconWithSize:(CGFloat)size;
+ (instancetype)iosSkipforwardOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosSnowyIconWithSize:(CGFloat)size;
+ (instancetype)iosSpeedometerIconWithSize:(CGFloat)size;
+ (instancetype)iosSpeedometerOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosStarIconWithSize:(CGFloat)size;
+ (instancetype)iosStarHalfIconWithSize:(CGFloat)size;
+ (instancetype)iosStarOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosStopwatchIconWithSize:(CGFloat)size;
+ (instancetype)iosStopwatchOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosSunnyIconWithSize:(CGFloat)size;
+ (instancetype)iosSunnyOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosTelephoneIconWithSize:(CGFloat)size;
+ (instancetype)iosTelephoneOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosTennisballIconWithSize:(CGFloat)size;
+ (instancetype)iosTennisballOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosThunderstormIconWithSize:(CGFloat)size;
+ (instancetype)iosThunderstormOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosTimeIconWithSize:(CGFloat)size;
+ (instancetype)iosTimeOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosTimerIconWithSize:(CGFloat)size;
+ (instancetype)iosTimerOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosToggleIconWithSize:(CGFloat)size;
+ (instancetype)iosToggleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosTrashIconWithSize:(CGFloat)size;
+ (instancetype)iosTrashOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosUndoIconWithSize:(CGFloat)size;
+ (instancetype)iosUndoOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosUnlockedIconWithSize:(CGFloat)size;
+ (instancetype)iosUnlockedOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosUploadIconWithSize:(CGFloat)size;
+ (instancetype)iosUploadOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosVideocamIconWithSize:(CGFloat)size;
+ (instancetype)iosVideocamOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosVolumeHighIconWithSize:(CGFloat)size;
+ (instancetype)iosVolumeLowIconWithSize:(CGFloat)size;
+ (instancetype)iosWineglassIconWithSize:(CGFloat)size;
+ (instancetype)iosWineglassOutlineIconWithSize:(CGFloat)size;
+ (instancetype)iosWorldIconWithSize:(CGFloat)size;
+ (instancetype)iosWorldOutlineIconWithSize:(CGFloat)size;
+ (instancetype)ipadIconWithSize:(CGFloat)size;
+ (instancetype)iphoneIconWithSize:(CGFloat)size;
+ (instancetype)ipodIconWithSize:(CGFloat)size;
+ (instancetype)jetIconWithSize:(CGFloat)size;
+ (instancetype)keyIconWithSize:(CGFloat)size;
+ (instancetype)knifeIconWithSize:(CGFloat)size;
+ (instancetype)laptopIconWithSize:(CGFloat)size;
+ (instancetype)leafIconWithSize:(CGFloat)size;
+ (instancetype)levelsIconWithSize:(CGFloat)size;
+ (instancetype)lightbulbIconWithSize:(CGFloat)size;
+ (instancetype)linkIconWithSize:(CGFloat)size;
+ (instancetype)loadAIconWithSize:(CGFloat)size;
+ (instancetype)loadBIconWithSize:(CGFloat)size;
+ (instancetype)loadCIconWithSize:(CGFloat)size;
+ (instancetype)loadDIconWithSize:(CGFloat)size;
+ (instancetype)locationIconWithSize:(CGFloat)size;
+ (instancetype)lockCombinationIconWithSize:(CGFloat)size;
+ (instancetype)lockedIconWithSize:(CGFloat)size;
+ (instancetype)logInIconWithSize:(CGFloat)size;
+ (instancetype)logOutIconWithSize:(CGFloat)size;
+ (instancetype)loopIconWithSize:(CGFloat)size;
+ (instancetype)magnetIconWithSize:(CGFloat)size;
+ (instancetype)maleIconWithSize:(CGFloat)size;
+ (instancetype)manIconWithSize:(CGFloat)size;
+ (instancetype)mapIconWithSize:(CGFloat)size;
+ (instancetype)medkitIconWithSize:(CGFloat)size;
+ (instancetype)mergeIconWithSize:(CGFloat)size;
+ (instancetype)micAIconWithSize:(CGFloat)size;
+ (instancetype)micBIconWithSize:(CGFloat)size;
+ (instancetype)micCIconWithSize:(CGFloat)size;
+ (instancetype)minusIconWithSize:(CGFloat)size;
+ (instancetype)minusCircledIconWithSize:(CGFloat)size;
+ (instancetype)minusRoundIconWithSize:(CGFloat)size;
+ (instancetype)modelSIconWithSize:(CGFloat)size;
+ (instancetype)monitorIconWithSize:(CGFloat)size;
+ (instancetype)moreIconWithSize:(CGFloat)size;
+ (instancetype)mouseIconWithSize:(CGFloat)size;
+ (instancetype)musicNoteIconWithSize:(CGFloat)size;
+ (instancetype)naviconIconWithSize:(CGFloat)size;
+ (instancetype)naviconRoundIconWithSize:(CGFloat)size;
+ (instancetype)navigateIconWithSize:(CGFloat)size;
+ (instancetype)networkIconWithSize:(CGFloat)size;
+ (instancetype)noSmokingIconWithSize:(CGFloat)size;
+ (instancetype)nuclearIconWithSize:(CGFloat)size;
+ (instancetype)outletIconWithSize:(CGFloat)size;
+ (instancetype)paintbrushIconWithSize:(CGFloat)size;
+ (instancetype)paintbucketIconWithSize:(CGFloat)size;
+ (instancetype)paperAirplaneIconWithSize:(CGFloat)size;
+ (instancetype)paperclipIconWithSize:(CGFloat)size;
+ (instancetype)pauseIconWithSize:(CGFloat)size;
+ (instancetype)personIconWithSize:(CGFloat)size;
+ (instancetype)personAddIconWithSize:(CGFloat)size;
+ (instancetype)personStalkerIconWithSize:(CGFloat)size;
+ (instancetype)pieGraphIconWithSize:(CGFloat)size;
+ (instancetype)pinIconWithSize:(CGFloat)size;
+ (instancetype)pinpointIconWithSize:(CGFloat)size;
+ (instancetype)pizzaIconWithSize:(CGFloat)size;
+ (instancetype)planeIconWithSize:(CGFloat)size;
+ (instancetype)planetIconWithSize:(CGFloat)size;
+ (instancetype)playIconWithSize:(CGFloat)size;
+ (instancetype)playstationIconWithSize:(CGFloat)size;
+ (instancetype)plusIconWithSize:(CGFloat)size;
+ (instancetype)plusCircledIconWithSize:(CGFloat)size;
+ (instancetype)plusRoundIconWithSize:(CGFloat)size;
+ (instancetype)podiumIconWithSize:(CGFloat)size;
+ (instancetype)poundIconWithSize:(CGFloat)size;
+ (instancetype)powerIconWithSize:(CGFloat)size;
+ (instancetype)pricetagIconWithSize:(CGFloat)size;
+ (instancetype)pricetagsIconWithSize:(CGFloat)size;
+ (instancetype)printerIconWithSize:(CGFloat)size;
+ (instancetype)pullRequestIconWithSize:(CGFloat)size;
+ (instancetype)qrScannerIconWithSize:(CGFloat)size;
+ (instancetype)quoteIconWithSize:(CGFloat)size;
+ (instancetype)radioWavesIconWithSize:(CGFloat)size;
+ (instancetype)recordIconWithSize:(CGFloat)size;
+ (instancetype)refreshIconWithSize:(CGFloat)size;
+ (instancetype)replyIconWithSize:(CGFloat)size;
+ (instancetype)replyAllIconWithSize:(CGFloat)size;
+ (instancetype)ribbonAIconWithSize:(CGFloat)size;
+ (instancetype)ribbonBIconWithSize:(CGFloat)size;
+ (instancetype)sadIconWithSize:(CGFloat)size;
+ (instancetype)sadOutlineIconWithSize:(CGFloat)size;
+ (instancetype)scissorsIconWithSize:(CGFloat)size;
+ (instancetype)searchIconWithSize:(CGFloat)size;
+ (instancetype)settingsIconWithSize:(CGFloat)size;
+ (instancetype)shareIconWithSize:(CGFloat)size;
+ (instancetype)shuffleIconWithSize:(CGFloat)size;
+ (instancetype)skipBackwardIconWithSize:(CGFloat)size;
+ (instancetype)skipForwardIconWithSize:(CGFloat)size;
+ (instancetype)socialAndroidIconWithSize:(CGFloat)size;
+ (instancetype)socialAndroidOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialAngularIconWithSize:(CGFloat)size;
+ (instancetype)socialAngularOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialAppleIconWithSize:(CGFloat)size;
+ (instancetype)socialAppleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialBitcoinIconWithSize:(CGFloat)size;
+ (instancetype)socialBitcoinOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialBufferIconWithSize:(CGFloat)size;
+ (instancetype)socialBufferOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialChromeIconWithSize:(CGFloat)size;
+ (instancetype)socialChromeOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialCodepenIconWithSize:(CGFloat)size;
+ (instancetype)socialCodepenOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialCss3IconWithSize:(CGFloat)size;
+ (instancetype)socialCss3OutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialDesignernewsIconWithSize:(CGFloat)size;
+ (instancetype)socialDesignernewsOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialDribbbleIconWithSize:(CGFloat)size;
+ (instancetype)socialDribbbleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialDropboxIconWithSize:(CGFloat)size;
+ (instancetype)socialDropboxOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialEuroIconWithSize:(CGFloat)size;
+ (instancetype)socialEuroOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialFacebookIconWithSize:(CGFloat)size;
+ (instancetype)socialFacebookOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialFoursquareIconWithSize:(CGFloat)size;
+ (instancetype)socialFoursquareOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialFreebsdDevilIconWithSize:(CGFloat)size;
+ (instancetype)socialGithubIconWithSize:(CGFloat)size;
+ (instancetype)socialGithubOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialGoogleIconWithSize:(CGFloat)size;
+ (instancetype)socialGoogleOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialGoogleplusIconWithSize:(CGFloat)size;
+ (instancetype)socialGoogleplusOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialHackernewsIconWithSize:(CGFloat)size;
+ (instancetype)socialHackernewsOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialHtml5IconWithSize:(CGFloat)size;
+ (instancetype)socialHtml5OutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialInstagramIconWithSize:(CGFloat)size;
+ (instancetype)socialInstagramOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialJavascriptIconWithSize:(CGFloat)size;
+ (instancetype)socialJavascriptOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialLinkedinIconWithSize:(CGFloat)size;
+ (instancetype)socialLinkedinOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialMarkdownIconWithSize:(CGFloat)size;
+ (instancetype)socialNodejsIconWithSize:(CGFloat)size;
+ (instancetype)socialOctocatIconWithSize:(CGFloat)size;
+ (instancetype)socialPinterestIconWithSize:(CGFloat)size;
+ (instancetype)socialPinterestOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialPythonIconWithSize:(CGFloat)size;
+ (instancetype)socialRedditIconWithSize:(CGFloat)size;
+ (instancetype)socialRedditOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialRssIconWithSize:(CGFloat)size;
+ (instancetype)socialRssOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialSassIconWithSize:(CGFloat)size;
+ (instancetype)socialSkypeIconWithSize:(CGFloat)size;
+ (instancetype)socialSkypeOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialSnapchatIconWithSize:(CGFloat)size;
+ (instancetype)socialSnapchatOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialTumblrIconWithSize:(CGFloat)size;
+ (instancetype)socialTumblrOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialTuxIconWithSize:(CGFloat)size;
+ (instancetype)socialTwitchIconWithSize:(CGFloat)size;
+ (instancetype)socialTwitchOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialTwitterIconWithSize:(CGFloat)size;
+ (instancetype)socialTwitterOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialUsdIconWithSize:(CGFloat)size;
+ (instancetype)socialUsdOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialVimeoIconWithSize:(CGFloat)size;
+ (instancetype)socialVimeoOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialWhatsappIconWithSize:(CGFloat)size;
+ (instancetype)socialWhatsappOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialWindowsIconWithSize:(CGFloat)size;
+ (instancetype)socialWindowsOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialWordpressIconWithSize:(CGFloat)size;
+ (instancetype)socialWordpressOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialYahooIconWithSize:(CGFloat)size;
+ (instancetype)socialYahooOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialYenIconWithSize:(CGFloat)size;
+ (instancetype)socialYenOutlineIconWithSize:(CGFloat)size;
+ (instancetype)socialYoutubeIconWithSize:(CGFloat)size;
+ (instancetype)socialYoutubeOutlineIconWithSize:(CGFloat)size;
+ (instancetype)soupCanIconWithSize:(CGFloat)size;
+ (instancetype)soupCanOutlineIconWithSize:(CGFloat)size;
+ (instancetype)speakerphoneIconWithSize:(CGFloat)size;
+ (instancetype)speedometerIconWithSize:(CGFloat)size;
+ (instancetype)spoonIconWithSize:(CGFloat)size;
+ (instancetype)starIconWithSize:(CGFloat)size;
+ (instancetype)statsBarsIconWithSize:(CGFloat)size;
+ (instancetype)steamIconWithSize:(CGFloat)size;
+ (instancetype)stopIconWithSize:(CGFloat)size;
+ (instancetype)thermometerIconWithSize:(CGFloat)size;
+ (instancetype)thumbsdownIconWithSize:(CGFloat)size;
+ (instancetype)thumbsupIconWithSize:(CGFloat)size;
+ (instancetype)toggleIconWithSize:(CGFloat)size;
+ (instancetype)toggleFilledIconWithSize:(CGFloat)size;
+ (instancetype)transgenderIconWithSize:(CGFloat)size;
+ (instancetype)trashAIconWithSize:(CGFloat)size;
+ (instancetype)trashBIconWithSize:(CGFloat)size;
+ (instancetype)trophyIconWithSize:(CGFloat)size;
+ (instancetype)tshirtIconWithSize:(CGFloat)size;
+ (instancetype)tshirtOutlineIconWithSize:(CGFloat)size;
+ (instancetype)umbrellaIconWithSize:(CGFloat)size;
+ (instancetype)universityIconWithSize:(CGFloat)size;
+ (instancetype)unlockedIconWithSize:(CGFloat)size;
+ (instancetype)uploadIconWithSize:(CGFloat)size;
+ (instancetype)usbIconWithSize:(CGFloat)size;
+ (instancetype)videocameraIconWithSize:(CGFloat)size;
+ (instancetype)volumeHighIconWithSize:(CGFloat)size;
+ (instancetype)volumeLowIconWithSize:(CGFloat)size;
+ (instancetype)volumeMediumIconWithSize:(CGFloat)size;
+ (instancetype)volumeMuteIconWithSize:(CGFloat)size;
+ (instancetype)wandIconWithSize:(CGFloat)size;
+ (instancetype)waterdropIconWithSize:(CGFloat)size;
+ (instancetype)wifiIconWithSize:(CGFloat)size;
+ (instancetype)wineglassIconWithSize:(CGFloat)size;
+ (instancetype)womanIconWithSize:(CGFloat)size;
+ (instancetype)wrenchIconWithSize:(CGFloat)size;
+ (instancetype)xboxIconWithSize:(CGFloat)size;

@end

@interface FAKIonIcons (Unavailable)

+ (instancetype)ios7AlarmIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAlarmIconWithSize: instead")));
+ (instancetype)ios7AlarmOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAlarmOutlineIconWithSize: instead")));
+ (instancetype)ios7AlbumsIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAlbumsIconWithSize: instead")));
+ (instancetype)ios7AlbumsOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAlbumsOutlineIconWithSize: instead")));
+ (instancetype)ios7AmericanfootballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAmericanfootballIconWithSize: instead")));
+ (instancetype)ios7AmericanfootballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAmericanfootballOutlineIconWithSize: instead")));
+ (instancetype)ios7AnalyticsIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAnalyticsIconWithSize: instead")));
+ (instancetype)ios7AnalyticsOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAnalyticsOutlineIconWithSize: instead")));
+ (instancetype)ios7ArrowBackIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowBackIconWithSize: instead")));
+ (instancetype)ios7ArrowDownIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowDownIconWithSize: instead")));
+ (instancetype)ios7ArrowForwardIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowForwardIconWithSize: instead")));
+ (instancetype)ios7ArrowLeftIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowLeftIconWithSize: instead")));
+ (instancetype)ios7ArrowRightIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowRightIconWithSize: instead")));
+ (instancetype)ios7ArrowThinDownIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowThinDownIconWithSize: instead")));
+ (instancetype)ios7ArrowThinLeftIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowThinLeftIconWithSize: instead")));
+ (instancetype)ios7ArrowThinRightIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowThinRightIconWithSize: instead")));
+ (instancetype)ios7ArrowThinUpIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowThinUpIconWithSize: instead")));
+ (instancetype)ios7ArrowUpIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosArrowUpIconWithSize: instead")));
+ (instancetype)ios7AtIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAtIconWithSize: instead")));
+ (instancetype)ios7AtOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosAtOutlineIconWithSize: instead")));
+ (instancetype)ios7BarcodeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBarcodeIconWithSize: instead")));
+ (instancetype)ios7BarcodeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBarcodeOutlineIconWithSize: instead")));
+ (instancetype)ios7BaseballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBaseballIconWithSize: instead")));
+ (instancetype)ios7BaseballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBaseballOutlineIconWithSize: instead")));
+ (instancetype)ios7BasketballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBasketballIconWithSize: instead")));
+ (instancetype)ios7BasketballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBasketballOutlineIconWithSize: instead")));
+ (instancetype)ios7BellIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBellIconWithSize: instead")));
+ (instancetype)ios7BellOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBellOutlineIconWithSize: instead")));
+ (instancetype)ios7BoltIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBoltIconWithSize: instead")));
+ (instancetype)ios7BoltOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBoltOutlineIconWithSize: instead")));
+ (instancetype)ios7BookmarksIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBookmarksIconWithSize: instead")));
+ (instancetype)ios7BookmarksOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBookmarksOutlineIconWithSize: instead")));
+ (instancetype)ios7BoxIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBoxIconWithSize: instead")));
+ (instancetype)ios7BoxOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBoxOutlineIconWithSize: instead")));
+ (instancetype)ios7BriefcaseIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBriefcaseIconWithSize: instead")));
+ (instancetype)ios7BriefcaseOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBriefcaseOutlineIconWithSize: instead")));
+ (instancetype)ios7BrowsersIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBrowsersIconWithSize: instead")));
+ (instancetype)ios7BrowsersOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosBrowsersOutlineIconWithSize: instead")));
+ (instancetype)ios7CalculatorIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCalculatorIconWithSize: instead")));
+ (instancetype)ios7CalculatorOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCalculatorOutlineIconWithSize: instead")));
+ (instancetype)ios7CalendarIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCalendarIconWithSize: instead")));
+ (instancetype)ios7CalendarOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCalendarOutlineIconWithSize: instead")));
+ (instancetype)ios7CameraIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCameraIconWithSize: instead")));
+ (instancetype)ios7CameraOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCameraOutlineIconWithSize: instead")));
+ (instancetype)ios7CartIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCartIconWithSize: instead")));
+ (instancetype)ios7CartOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCartOutlineIconWithSize: instead")));
+ (instancetype)ios7ChatboxesIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosChatboxesIconWithSize: instead")));
+ (instancetype)ios7ChatboxesOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosChatboxesOutlineIconWithSize: instead")));
+ (instancetype)ios7ChatbubbleIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosChatbubbleIconWithSize: instead")));
+ (instancetype)ios7ChatbubbleOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosChatbubbleOutlineIconWithSize: instead")));
+ (instancetype)ios7CheckmarkIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCheckmarkIconWithSize: instead")));
+ (instancetype)ios7CheckmarkEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCheckmarkEmptyIconWithSize: instead")));
+ (instancetype)ios7CheckmarkOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCheckmarkOutlineIconWithSize: instead")));
+ (instancetype)ios7CircleFilledIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCircleFilledIconWithSize: instead")));
+ (instancetype)ios7CircleOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCircleOutlineIconWithSize: instead")));
+ (instancetype)ios7ClockIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosClockIconWithSize: instead")));
+ (instancetype)ios7ClockOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosClockOutlineIconWithSize: instead")));
+ (instancetype)ios7CloseIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloseIconWithSize: instead")));
+ (instancetype)ios7CloseEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloseEmptyIconWithSize: instead")));
+ (instancetype)ios7CloseOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloseOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudIconWithSize: instead")));
+ (instancetype)ios7CloudDownloadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudDownloadIconWithSize: instead")));
+ (instancetype)ios7CloudDownloadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudDownloadOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudUploadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudUploadIconWithSize: instead")));
+ (instancetype)ios7CloudUploadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudUploadOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudyIconWithSize: instead")));
+ (instancetype)ios7CloudyNightIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudyNightIconWithSize: instead")));
+ (instancetype)ios7CloudyNightOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudyNightOutlineIconWithSize: instead")));
+ (instancetype)ios7CloudyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCloudyOutlineIconWithSize: instead")));
+ (instancetype)ios7CogIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCogIconWithSize: instead")));
+ (instancetype)ios7CogOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCogOutlineIconWithSize: instead")));
+ (instancetype)ios7ComposeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosComposeIconWithSize: instead")));
+ (instancetype)ios7ComposeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosComposeOutlineIconWithSize: instead")));
+ (instancetype)ios7ContactIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosContactIconWithSize: instead")));
+ (instancetype)ios7ContactOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosContactOutlineIconWithSize: instead")));
+ (instancetype)ios7CopyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCopyIconWithSize: instead")));
+ (instancetype)ios7CopyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosCopyOutlineIconWithSize: instead")));
+ (instancetype)ios7DownloadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosDownloadIconWithSize: instead")));
+ (instancetype)ios7DownloadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosDownloadOutlineIconWithSize: instead")));
+ (instancetype)ios7DragIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosDragIconWithSize: instead")));
+ (instancetype)ios7EmailIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosEmailIconWithSize: instead")));
+ (instancetype)ios7EmailOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosEmailOutlineIconWithSize: instead")));
+ (instancetype)ios7ExpandIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosExpandIconWithSize: instead")));
+ (instancetype)ios7EyeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosEyeIconWithSize: instead")));
+ (instancetype)ios7EyeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosEyeOutlineIconWithSize: instead")));
+ (instancetype)ios7FastforwardIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFastforwardIconWithSize: instead")));
+ (instancetype)ios7FastforwardOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFastforwardOutlineIconWithSize: instead")));
+ (instancetype)ios7FilingIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFilingIconWithSize: instead")));
+ (instancetype)ios7FilingOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFilingOutlineIconWithSize: instead")));
+ (instancetype)ios7FilmIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFilmIconWithSize: instead")));
+ (instancetype)ios7FilmOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFilmOutlineIconWithSize: instead")));
+ (instancetype)ios7FlagIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFlagIconWithSize: instead")));
+ (instancetype)ios7FlagOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFlagOutlineIconWithSize: instead")));
+ (instancetype)ios7FolderIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFolderIconWithSize: instead")));
+ (instancetype)ios7FolderOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFolderOutlineIconWithSize: instead")));
+ (instancetype)ios7FootballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFootballIconWithSize: instead")));
+ (instancetype)ios7FootballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosFootballOutlineIconWithSize: instead")));
+ (instancetype)ios7GearIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosGearIconWithSize: instead")));
+ (instancetype)ios7GearOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosGearOutlineIconWithSize: instead")));
+ (instancetype)ios7GlassesIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosGlassesIconWithSize: instead")));
+ (instancetype)ios7GlassesOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosGlassesOutlineIconWithSize: instead")));
+ (instancetype)ios7HeartIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHeartIconWithSize: instead")));
+ (instancetype)ios7HeartOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHeartOutlineIconWithSize: instead")));
+ (instancetype)ios7HelpIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHelpIconWithSize: instead")));
+ (instancetype)ios7HelpEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHelpEmptyIconWithSize: instead")));
+ (instancetype)ios7HelpOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHelpOutlineIconWithSize: instead")));
+ (instancetype)ios7HomeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHomeIconWithSize: instead")));
+ (instancetype)ios7HomeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosHomeOutlineIconWithSize: instead")));
+ (instancetype)ios7InfiniteIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInfiniteIconWithSize: instead")));
+ (instancetype)ios7InfiniteOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInfiniteOutlineIconWithSize: instead")));
+ (instancetype)ios7InformationIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInformationIconWithSize: instead")));
+ (instancetype)ios7InformationEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInformationEmptyIconWithSize: instead")));
+ (instancetype)ios7InformationOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosInformationOutlineIconWithSize: instead")));
+ (instancetype)ios7IonicOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosIonicOutlineIconWithSize: instead")));
+ (instancetype)ios7KeypadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosKeypadIconWithSize: instead")));
+ (instancetype)ios7KeypadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosKeypadOutlineIconWithSize: instead")));
+ (instancetype)ios7LightbulbIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLightbulbIconWithSize: instead")));
+ (instancetype)ios7LightbulbOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLightbulbOutlineIconWithSize: instead")));
+ (instancetype)ios7LocationIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLocationIconWithSize: instead")));
+ (instancetype)ios7LocationOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLocationOutlineIconWithSize: instead")));
+ (instancetype)ios7LockedIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLockedIconWithSize: instead")));
+ (instancetype)ios7LockedOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLockedOutlineIconWithSize: instead")));
+ (instancetype)ios7LoopIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLoopIconWithSize: instead")));
+ (instancetype)ios7LoopStrongIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosLoopStrongIconWithSize: instead")));
+ (instancetype)ios7MedkitIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMedkitIconWithSize: instead")));
+ (instancetype)ios7MedkitOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMedkitOutlineIconWithSize: instead")));
+ (instancetype)ios7MicIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMicIconWithSize: instead")));
+ (instancetype)ios7MicOffIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMicOffIconWithSize: instead")));
+ (instancetype)ios7MicOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMicOutlineIconWithSize: instead")));
+ (instancetype)ios7MinusIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMinusIconWithSize: instead")));
+ (instancetype)ios7MinusEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMinusEmptyIconWithSize: instead")));
+ (instancetype)ios7MinusOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMinusOutlineIconWithSize: instead")));
+ (instancetype)ios7MonitorIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMonitorIconWithSize: instead")));
+ (instancetype)ios7MonitorOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMonitorOutlineIconWithSize: instead")));
+ (instancetype)ios7MoonIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMoonIconWithSize: instead")));
+ (instancetype)ios7MoonOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMoonOutlineIconWithSize: instead")));
+ (instancetype)ios7MoreIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMoreIconWithSize: instead")));
+ (instancetype)ios7MoreOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMoreOutlineIconWithSize: instead")));
+ (instancetype)ios7MusicalNoteIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMusicalNoteIconWithSize: instead")));
+ (instancetype)ios7MusicalNotesIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosMusicalNotesIconWithSize: instead")));
+ (instancetype)ios7NavigateIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosNavigateIconWithSize: instead")));
+ (instancetype)ios7NavigateOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosNavigateOutlineIconWithSize: instead")));
+ (instancetype)ios7PaperIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPaperIconWithSize: instead")));
+ (instancetype)ios7PaperOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPaperOutlineIconWithSize: instead")));
+ (instancetype)ios7PaperplaneIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPaperplaneIconWithSize: instead")));
+ (instancetype)ios7PaperplaneOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPaperplaneOutlineIconWithSize: instead")));
+ (instancetype)ios7PartlysunnyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPartlysunnyIconWithSize: instead")));
+ (instancetype)ios7PartlysunnyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPartlysunnyOutlineIconWithSize: instead")));
+ (instancetype)ios7PauseIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPauseIconWithSize: instead")));
+ (instancetype)ios7PauseOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPauseOutlineIconWithSize: instead")));
+ (instancetype)ios7PawIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPawIconWithSize: instead")));
+ (instancetype)ios7PawOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPawOutlineIconWithSize: instead")));
+ (instancetype)ios7PeopleIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPeopleIconWithSize: instead")));
+ (instancetype)ios7PeopleOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPeopleOutlineIconWithSize: instead")));
+ (instancetype)ios7PersonIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPersonIconWithSize: instead")));
+ (instancetype)ios7PersonOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPersonOutlineIconWithSize: instead")));
+ (instancetype)ios7PersonaddIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPersonaddIconWithSize: instead")));
+ (instancetype)ios7PersonaddOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPersonaddOutlineIconWithSize: instead")));
+ (instancetype)ios7PhotosIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPhotosIconWithSize: instead")));
+ (instancetype)ios7PhotosOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPhotosOutlineIconWithSize: instead")));
+ (instancetype)ios7PieIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPieIconWithSize: instead")));
+ (instancetype)ios7PieOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPieOutlineIconWithSize: instead")));
+ (instancetype)ios7PlayIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlayIconWithSize: instead")));
+ (instancetype)ios7PlayOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlayOutlineIconWithSize: instead")));
+ (instancetype)ios7PlusIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlusIconWithSize: instead")));
+ (instancetype)ios7PlusEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlusEmptyIconWithSize: instead")));
+ (instancetype)ios7PlusOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPlusOutlineIconWithSize: instead")));
+ (instancetype)ios7PricetagIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPricetagIconWithSize: instead")));
+ (instancetype)ios7PricetagOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPricetagOutlineIconWithSize: instead")));
+ (instancetype)ios7PricetagsIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPricetagsIconWithSize: instead")));
+ (instancetype)ios7PricetagsOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPricetagsOutlineIconWithSize: instead")));
+ (instancetype)ios7PrinterIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPrinterIconWithSize: instead")));
+ (instancetype)ios7PrinterOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPrinterOutlineIconWithSize: instead")));
+ (instancetype)ios7PulseIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPulseIconWithSize: instead")));
+ (instancetype)ios7PulseStrongIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosPulseStrongIconWithSize: instead")));
+ (instancetype)ios7RainyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRainyIconWithSize: instead")));
+ (instancetype)ios7RainyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRainyOutlineIconWithSize: instead")));
+ (instancetype)ios7RecordingIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRecordingIconWithSize: instead")));
+ (instancetype)ios7RecordingOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRecordingOutlineIconWithSize: instead")));
+ (instancetype)ios7RedoIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRedoIconWithSize: instead")));
+ (instancetype)ios7RedoOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRedoOutlineIconWithSize: instead")));
+ (instancetype)ios7RefreshIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRefreshIconWithSize: instead")));
+ (instancetype)ios7RefreshEmptyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRefreshEmptyIconWithSize: instead")));
+ (instancetype)ios7RefreshOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRefreshOutlineIconWithSize: instead")));
+ (instancetype)ios7ReloadbeforeionIos7ReloadingIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosReloadbeforeionIos7ReloadingIconWithSize: instead")));
+ (instancetype)ios7ReverseCameraIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosReverseCameraIconWithSize: instead")));
+ (instancetype)ios7ReverseCameraOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosReverseCameraOutlineIconWithSize: instead")));
+ (instancetype)ios7RewindIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRewindIconWithSize: instead")));
+ (instancetype)ios7RewindOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosRewindOutlineIconWithSize: instead")));
+ (instancetype)ios7SearchIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSearchIconWithSize: instead")));
+ (instancetype)ios7SearchStrongIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSearchStrongIconWithSize: instead")));
+ (instancetype)ios7SettingsIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSettingsIconWithSize: instead")));
+ (instancetype)ios7SettingsStrongIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSettingsStrongIconWithSize: instead")));
+ (instancetype)ios7ShrinkIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosShrinkIconWithSize: instead")));
+ (instancetype)ios7SkipbackwardIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSkipbackwardIconWithSize: instead")));
+ (instancetype)ios7SkipbackwardOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSkipbackwardOutlineIconWithSize: instead")));
+ (instancetype)ios7SkipforwardIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSkipforwardIconWithSize: instead")));
+ (instancetype)ios7SkipforwardOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSkipforwardOutlineIconWithSize: instead")));
+ (instancetype)ios7SnowyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSnowyIconWithSize: instead")));
+ (instancetype)ios7SpeedometerIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSpeedometerIconWithSize: instead")));
+ (instancetype)ios7SpeedometerOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSpeedometerOutlineIconWithSize: instead")));
+ (instancetype)ios7StarIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStarIconWithSize: instead")));
+ (instancetype)ios7StarHalfIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStarHalfIconWithSize: instead")));
+ (instancetype)ios7StarOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStarOutlineIconWithSize: instead")));
+ (instancetype)ios7StopwatchIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStopwatchIconWithSize: instead")));
+ (instancetype)ios7StopwatchOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosStopwatchOutlineIconWithSize: instead")));
+ (instancetype)ios7SunnyIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSunnyIconWithSize: instead")));
+ (instancetype)ios7SunnyOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosSunnyOutlineIconWithSize: instead")));
+ (instancetype)ios7TelephoneIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTelephoneIconWithSize: instead")));
+ (instancetype)ios7TelephoneOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTelephoneOutlineIconWithSize: instead")));
+ (instancetype)ios7TennisballIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTennisballIconWithSize: instead")));
+ (instancetype)ios7TennisballOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTennisballOutlineIconWithSize: instead")));
+ (instancetype)ios7ThunderstormIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosThunderstormIconWithSize: instead")));
+ (instancetype)ios7ThunderstormOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosThunderstormOutlineIconWithSize: instead")));
+ (instancetype)ios7TimeIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTimeIconWithSize: instead")));
+ (instancetype)ios7TimeOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTimeOutlineIconWithSize: instead")));
+ (instancetype)ios7TimerIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTimerIconWithSize: instead")));
+ (instancetype)ios7TimerOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTimerOutlineIconWithSize: instead")));
+ (instancetype)ios7ToggleIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosToggleIconWithSize: instead")));
+ (instancetype)ios7ToggleOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosToggleOutlineIconWithSize: instead")));
+ (instancetype)ios7TrashIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTrashIconWithSize: instead")));
+ (instancetype)ios7TrashOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosTrashOutlineIconWithSize: instead")));
+ (instancetype)ios7UndoIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUndoIconWithSize: instead")));
+ (instancetype)ios7UndoOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUndoOutlineIconWithSize: instead")));
+ (instancetype)ios7UnlockedIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUnlockedIconWithSize: instead")));
+ (instancetype)ios7UnlockedOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUnlockedOutlineIconWithSize: instead")));
+ (instancetype)ios7UploadIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUploadIconWithSize: instead")));
+ (instancetype)ios7UploadOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosUploadOutlineIconWithSize: instead")));
+ (instancetype)ios7VideocamIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosVideocamIconWithSize: instead")));
+ (instancetype)ios7VideocamOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosVideocamOutlineIconWithSize: instead")));
+ (instancetype)ios7VolumeHighIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosVolumeHighIconWithSize: instead")));
+ (instancetype)ios7VolumeLowIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosVolumeLowIconWithSize: instead")));
+ (instancetype)ios7WineglassIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosWineglassIconWithSize: instead")));
+ (instancetype)ios7WineglassOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosWineglassOutlineIconWithSize: instead")));
+ (instancetype)ios7WorldIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosWorldIconWithSize: instead")));
+ (instancetype)ios7WorldOutlineIconWithSize:(CGFloat)size __attribute__((unavailable("Use +iosWorldOutlineIconWithSize: instead")));

@end
